# initial_mssql
"""initial_mssql

Revision ID: 70df5e4506d5
Revises: 
Create Date: 2026-04-14 21:34:59.886415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70df5e4506d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('board', sa.String(length=50), nullable=True),
    sa.Column('medium', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.String(50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('departments',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('head_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    # head_id FK to staff added below after staff table is created (circular dep)
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_school_id'), 'departments', ['school_id'], unique=False)
    op.create_table('permissions',
    sa.Column('module', sa.String(length=60), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('designation_id', sa.Uuid(), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('employment_type', sa.Enum('permanent', 'contract', 'part_time', 'probation', name='employment_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('salary_type', sa.Enum('monthly', 'hourly', 'daily', name='salary_type'), nullable=False),
    sa.Column('monthly_salary', sa.Integer(), nullable=False),
    sa.Column('bank_account_no', sa.String(length=30), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_contact', sa.JSON(), nullable=True),
    sa.Column('qualifications', sa.JSON(), nullable=False),
    sa.Column('experience_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_staff_employee_id'), 'staff', ['employee_id'], unique=False)
    op.create_index(op.f('ix_staff_school_id'), 'staff', ['school_id'], unique=False)
    # Add deferred FK: departments.head_id -> staff.id (circular dep resolved)
    op.create_foreign_key('fk_departments_head_id_staff', 'departments', 'staff', ['head_id'], ['id'])
    op.create_table('academic_years',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('end_date > start_date', name='chk_academic_year_dates'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_years_school_id'), 'academic_years', ['school_id'], unique=False)
    op.create_table('designations',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_designations_school_id'), 'designations', ['school_id'], unique=False)
    op.create_table('fee_categories',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='fee_categories_school_id_name_key')
    )
    op.create_index(op.f('ix_fee_categories_school_id'), 'fee_categories', ['school_id'], unique=False)
    op.create_table('fee_discounts',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('percentage', 'fixed', name='discount_type'), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('applicable_to', sa.Enum('student', 'category', 'class_', name='discount_applicable_to'), nullable=False),
    sa.Column('nature', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_discounts_school_id'), 'fee_discounts', ['school_id'], unique=False)
    op.create_table('fine_configurations',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('fixed', 'percentage_per_day', name='fine_calc_type'), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('applicable_after_days', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fine_configurations_school_id'), 'fine_configurations', ['school_id'], unique=False)
    op.create_table('leave_types',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('max_days_per_year', sa.SmallInteger(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_types_school_id'), 'leave_types', ['school_id'], unique=False)
    op.create_table('roles',
    sa.Column('school_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_school_id'), 'roles', ['school_id'], unique=False)
    op.create_table('school_profile',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('favicon_url', sa.Text(), nullable=True),
    sa.Column('established_year', sa.SmallInteger(), nullable=True),
    sa.Column('affiliation_board', sa.String(length=100), nullable=True),
    sa.Column('affiliation_number', sa.String(length=100), nullable=True),
    sa.Column('principal_name', sa.String(length=150), nullable=True),
    sa.Column('principal_signature_url', sa.Text(), nullable=True),
    sa.Column('school_seal_url', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=20), nullable=False),
    sa.Column('date_format', sa.String(length=30), nullable=False),
    sa.Column('academic_start_month', sa.SmallInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    op.create_table('staff_attendance',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('present', 'absent', 'late', 'half_day', 'on_leave', 'holiday', name='staff_attendance_status'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'biometric', 'qr', name='attendance_source'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'date', name='staff_attendance_staff_id_date_key')
    )
    op.create_index(op.f('ix_staff_attendance_date'), 'staff_attendance', ['date'], unique=False)
    op.create_index(op.f('ix_staff_attendance_school_id'), 'staff_attendance', ['school_id'], unique=False)
    op.create_index(op.f('ix_staff_attendance_staff_id'), 'staff_attendance', ['staff_id'], unique=False)
    op.create_table('staff_documents',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('doc_type', sa.String(length=60), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_documents_school_id'), 'staff_documents', ['school_id'], unique=False)
    op.create_index(op.f('ix_staff_documents_staff_id'), 'staff_documents', ['staff_id'], unique=False)
    op.create_table('subjects',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('is_elective', sa.Boolean(), nullable=False),
    sa.Column('full_marks', sa.SmallInteger(), nullable=False),
    sa.Column('pass_marks', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'code', name='uq_subject_code_per_school')
    )
    op.create_index(op.f('ix_subjects_school_id'), 'subjects', ['school_id'], unique=False)
    op.create_table('users',
    sa.Column('school_id', sa.Uuid(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('otp_secret', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_school_id'), 'users', ['school_id'], unique=False)
    op.create_table('academic_terms',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('end_date > start_date', name='chk_academic_term_dates'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_terms_academic_year_id'), 'academic_terms', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_academic_terms_school_id'), 'academic_terms', ['school_id'], unique=False)
    op.create_table('admission_form_configs',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('fields_config', sa.JSON(), nullable=False),
    sa.Column('required_documents', sa.JSON(), nullable=False),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admission_form_configs_academic_year_id'), 'admission_form_configs', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_admission_form_configs_school_id'), 'admission_form_configs', ['school_id'], unique=False)
    op.create_table('admission_forms',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('reference_number', sa.String(length=30), nullable=False),
    sa.Column('applicant_name', sa.String(length=200), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('applying_for_class_id', sa.Uuid(), nullable=True),
    sa.Column('parent_name', sa.String(length=200), nullable=True),
    sa.Column('parent_phone', sa.String(length=20), nullable=True),
    sa.Column('parent_email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('previous_school', sa.String(length=200), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'under_review', 'approved', 'rejected', 'waitlisted', name='admission_status'), nullable=False),
    sa.Column('assigned_admission_number', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'reference_number', name='uq_admission_ref_per_school')
    )
    op.create_index(op.f('ix_admission_forms_academic_year_id'), 'admission_forms', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_admission_forms_school_id'), 'admission_forms', ['school_id'], unique=False)
    op.create_table('classes',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('numeric_level', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'academic_year_id', 'name', name='uq_class_per_school_year')
    )
    op.create_index(op.f('ix_classes_academic_year_id'), 'classes', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_classes_school_id'), 'classes', ['school_id'], unique=False)
    op.create_table('holidays',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('national', 'state', 'school', 'religious', 'other', name='holiday_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'date', name='holidays_school_id_date_key')
    )
    op.create_index(op.f('ix_holidays_academic_year_id'), 'holidays', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_holidays_date'), 'holidays', ['date'], unique=False)
    op.create_index(op.f('ix_holidays_school_id'), 'holidays', ['school_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('school_settings',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'key', name='uq_school_setting_key')
    )
    op.create_index(op.f('ix_school_settings_school_id'), 'school_settings', ['school_id'], unique=False)
    op.create_table('staff_leave_balances',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('leave_type_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('entitled_days', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('used_days', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_leave_balances_school_id'), 'staff_leave_balances', ['school_id'], unique=False)
    op.create_index(op.f('ix_staff_leave_balances_staff_id'), 'staff_leave_balances', ['staff_id'], unique=False)
    op.create_table('staff_leaves',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('leave_type_id', sa.Uuid(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('days_count', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='leave_status'), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_leaves_school_id'), 'staff_leaves', ['school_id'], unique=False)
    op.create_index(op.f('ix_staff_leaves_staff_id'), 'staff_leaves', ['staff_id'], unique=False)
    op.create_table('staff_payrolls',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('basic_salary', sa.Integer(), nullable=False),
    sa.Column('allowances', sa.JSON(), nullable=False),
    sa.Column('deductions', sa.JSON(), nullable=False),
    sa.Column('gross_salary', sa.Integer(), nullable=False),
    sa.Column('net_salary', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.Enum('cash', 'cheque', 'online', 'card', 'neft', 'upi', name='payment_method'), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('receipt_url', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_payrolls_school_id'), 'staff_payrolls', ['school_id'], unique=False)
    op.create_index(op.f('ix_staff_payrolls_staff_id'), 'staff_payrolls', ['staff_id'], unique=False)
    op.create_table('students',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('admission_number', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('nationality', sa.String(length=60), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_students_admission_number'), 'students', ['admission_number'], unique=False)
    op.create_index(op.f('ix_students_school_id'), 'students', ['school_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('class_subjects',
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'subject_id', name='uq_class_subject')
    )
    op.create_index(op.f('ix_class_subjects_class_id'), 'class_subjects', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_subjects_subject_id'), 'class_subjects', ['subject_id'], unique=False)
    op.create_table('fee_invoices',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('unpaid', 'partial', 'paid', 'overdue', 'waived', 'cancelled', name='invoice_status'), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('paid_amount', sa.Integer(), nullable=False),
    sa.Column('balance_amount', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'invoice_number', name='fee_invoices_school_id_invoice_number_key')
    )
    op.create_index(op.f('ix_fee_invoices_academic_year_id'), 'fee_invoices', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_fee_invoices_school_id'), 'fee_invoices', ['school_id'], unique=False)
    op.create_index(op.f('ix_fee_invoices_student_id'), 'fee_invoices', ['student_id'], unique=False)
    op.create_table('fee_structures',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('fee_category_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Enum('monthly', 'quarterly', 'annual', 'one_time', 'semi_annual', name='fee_frequency'), nullable=False),
    sa.Column('due_day', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['fee_category_id'], ['fee_categories.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'academic_year_id', 'class_id', 'fee_category_id', name='uq_fee_structures_school_year_class_cat')
    )
    op.create_index(op.f('ix_fee_structures_academic_year_id'), 'fee_structures', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_fee_structures_class_id'), 'fee_structures', ['class_id'], unique=False)
    op.create_index(op.f('ix_fee_structures_fee_category_id'), 'fee_structures', ['fee_category_id'], unique=False)
    op.create_index(op.f('ix_fee_structures_school_id'), 'fee_structures', ['school_id'], unique=False)
    op.create_table('sections',
    sa.Column('school_id', sa.Uuid(), nullable=True),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('max_students', sa.SmallInteger(), nullable=False),
    sa.Column('class_teacher_id', sa.Uuid(), nullable=True),
    sa.Column('room_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'name', name='uq_section_name_per_class')
    )
    op.create_index(op.f('ix_sections_class_id'), 'sections', ['class_id'], unique=False)
    op.create_index(op.f('ix_sections_class_teacher_id'), 'sections', ['class_teacher_id'], unique=False)
    op.create_index(op.f('ix_sections_school_id'), 'sections', ['school_id'], unique=False)
    op.create_table('student_discount_assignments',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('discount_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['discount_id'], ['fee_discounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'student_id', 'discount_id', 'academic_year_id', name='uq_student_discount_year')
    )
    op.create_index(op.f('ix_student_discount_assignments_academic_year_id'), 'student_discount_assignments', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_student_discount_assignments_discount_id'), 'student_discount_assignments', ['discount_id'], unique=False)
    op.create_index(op.f('ix_student_discount_assignments_school_id'), 'student_discount_assignments', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_discount_assignments_student_id'), 'student_discount_assignments', ['student_id'], unique=False)
    op.create_table('student_documents',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('doc_type', sa.String(length=60), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_documents_school_id'), 'student_documents', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_documents_student_id'), 'student_documents', ['student_id'], unique=False)
    op.create_table('student_parents',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('relation', sa.Enum('father', 'mother', 'guardian', 'sibling', 'other', name='parent_relation'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=False),
    sa.Column('can_access_portal', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_parents_school_id'), 'student_parents', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_parents_student_id'), 'student_parents', ['student_id'], unique=False)
    op.create_table('student_promotions',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('from_class_id', sa.Uuid(), nullable=False),
    sa.Column('to_class_id', sa.Uuid(), nullable=False),
    sa.Column('from_year_id', sa.Uuid(), nullable=False),
    sa.Column('to_year_id', sa.Uuid(), nullable=False),
    sa.Column('promoted_by', sa.Uuid(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['from_class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['from_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['promoted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['to_year_id'], ['academic_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_promotions_school_id'), 'student_promotions', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_promotions_student_id'), 'student_promotions', ['student_id'], unique=False)
    op.create_table('student_transfers',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('transfer_certificate_no', sa.String(length=50), nullable=False),
    sa.Column('leaving_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('issued_by', sa.Uuid(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_transfers_school_id'), 'student_transfers', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_transfers_student_id'), 'student_transfers', ['student_id'], unique=False)
    op.create_table('attendance_sessions',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('session_type', sa.Enum('morning', 'afternoon', 'full_day', name='session_type'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('taken_by', sa.Uuid(), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['taken_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'date', 'session_type', name='attendance_sessions_section_id_date_session_type_key')
    )
    op.create_index(op.f('ix_attendance_sessions_class_id'), 'attendance_sessions', ['class_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_date'), 'attendance_sessions', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_school_id'), 'attendance_sessions', ['school_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_section_id'), 'attendance_sessions', ['section_id'], unique=False)
    op.create_table('fee_invoice_items',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('fee_category_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('discount_amt', sa.Integer(), nullable=False),
    sa.Column('fine_applied', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['fee_category_id'], ['fee_categories.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['fee_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_invoice_items_fee_category_id'), 'fee_invoice_items', ['fee_category_id'], unique=False)
    op.create_index(op.f('ix_fee_invoice_items_invoice_id'), 'fee_invoice_items', ['invoice_id'], unique=False)
    op.create_table('fee_payments',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'cheque', 'online', 'card', 'neft', 'upi', name='payment_method'), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('collected_by', sa.Uuid(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=False),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['fee_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'receipt_number', name='fee_payments_school_id_receipt_number_key')
    )
    op.create_index(op.f('ix_fee_payments_invoice_id'), 'fee_payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_fee_payments_school_id'), 'fee_payments', ['school_id'], unique=False)
    op.create_table('student_enrollments',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('roll_number', sa.String(length=20), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_enrollments_academic_year_id'), 'student_enrollments', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_student_enrollments_school_id'), 'student_enrollments', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_enrollments_student_id'), 'student_enrollments', ['student_id'], unique=False)
    op.create_table('student_fee_assignments',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('fee_structure_id', sa.Uuid(), nullable=False),
    sa.Column('discount_id', sa.Uuid(), nullable=True),
    sa.Column('custom_amount', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['discount_id'], ['fee_discounts.id'], ),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'fee_structure_id', 'academic_year_id', name='uq_fee_assignments_student_structure_year')
    )
    op.create_index(op.f('ix_student_fee_assignments_academic_year_id'), 'student_fee_assignments', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_student_fee_assignments_fee_structure_id'), 'student_fee_assignments', ['fee_structure_id'], unique=False)
    op.create_index(op.f('ix_student_fee_assignments_school_id'), 'student_fee_assignments', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_fee_assignments_student_id'), 'student_fee_assignments', ['student_id'], unique=False)
    op.create_table('timetables',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=True),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('period_number', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='chk_timetable_end_after_start'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'academic_year_id', 'day_of_week', 'period_number', name='uq_timetable_slot')
    )
    op.create_index(op.f('ix_timetables_academic_year_id'), 'timetables', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_timetables_school_id'), 'timetables', ['school_id'], unique=False)
    op.create_index(op.f('ix_timetables_section_id'), 'timetables', ['section_id'], unique=False)
    op.create_index(op.f('ix_timetables_teacher_id'), 'timetables', ['teacher_id'], unique=False)
    op.create_table('student_attendance',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('present', 'absent', 'late', 'half_day', 'leave', 'holiday', name='student_attendance_status'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='student_attendance_session_id_student_id_key')
    )
    op.create_index(op.f('ix_student_attendance_school_id'), 'student_attendance', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_attendance_session_id'), 'student_attendance', ['session_id'], unique=False)
    op.create_index(op.f('ix_student_attendance_student_id'), 'student_attendance', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_attendance_student_id'), table_name='student_attendance')
    op.drop_index(op.f('ix_student_attendance_session_id'), table_name='student_attendance')
    op.drop_index(op.f('ix_student_attendance_school_id'), table_name='student_attendance')
    op.drop_table('student_attendance')
    op.drop_index(op.f('ix_timetables_teacher_id'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_section_id'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_school_id'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_academic_year_id'), table_name='timetables')
    op.drop_table('timetables')
    op.drop_index(op.f('ix_student_fee_assignments_student_id'), table_name='student_fee_assignments')
    op.drop_index(op.f('ix_student_fee_assignments_school_id'), table_name='student_fee_assignments')
    op.drop_index(op.f('ix_student_fee_assignments_fee_structure_id'), table_name='student_fee_assignments')
    op.drop_index(op.f('ix_student_fee_assignments_academic_year_id'), table_name='student_fee_assignments')
    op.drop_table('student_fee_assignments')
    op.drop_index(op.f('ix_student_enrollments_student_id'), table_name='student_enrollments')
    op.drop_index(op.f('ix_student_enrollments_school_id'), table_name='student_enrollments')
    op.drop_index(op.f('ix_student_enrollments_academic_year_id'), table_name='student_enrollments')
    op.drop_table('student_enrollments')
    op.drop_index(op.f('ix_fee_payments_school_id'), table_name='fee_payments')
    op.drop_index(op.f('ix_fee_payments_invoice_id'), table_name='fee_payments')
    op.drop_table('fee_payments')
    op.drop_index(op.f('ix_fee_invoice_items_invoice_id'), table_name='fee_invoice_items')
    op.drop_index(op.f('ix_fee_invoice_items_fee_category_id'), table_name='fee_invoice_items')
    op.drop_table('fee_invoice_items')
    op.drop_index(op.f('ix_attendance_sessions_section_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_school_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_date'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_class_id'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index(op.f('ix_student_transfers_student_id'), table_name='student_transfers')
    op.drop_index(op.f('ix_student_transfers_school_id'), table_name='student_transfers')
    op.drop_table('student_transfers')
    op.drop_index(op.f('ix_student_promotions_student_id'), table_name='student_promotions')
    op.drop_index(op.f('ix_student_promotions_school_id'), table_name='student_promotions')
    op.drop_table('student_promotions')
    op.drop_index(op.f('ix_student_parents_student_id'), table_name='student_parents')
    op.drop_index(op.f('ix_student_parents_school_id'), table_name='student_parents')
    op.drop_table('student_parents')
    op.drop_index(op.f('ix_student_documents_student_id'), table_name='student_documents')
    op.drop_index(op.f('ix_student_documents_school_id'), table_name='student_documents')
    op.drop_table('student_documents')
    op.drop_index(op.f('ix_student_discount_assignments_student_id'), table_name='student_discount_assignments')
    op.drop_index(op.f('ix_student_discount_assignments_school_id'), table_name='student_discount_assignments')
    op.drop_index(op.f('ix_student_discount_assignments_discount_id'), table_name='student_discount_assignments')
    op.drop_index(op.f('ix_student_discount_assignments_academic_year_id'), table_name='student_discount_assignments')
    op.drop_table('student_discount_assignments')
    op.drop_index(op.f('ix_sections_school_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_class_teacher_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_class_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_fee_structures_school_id'), table_name='fee_structures')
    op.drop_index(op.f('ix_fee_structures_fee_category_id'), table_name='fee_structures')
    op.drop_index(op.f('ix_fee_structures_class_id'), table_name='fee_structures')
    op.drop_index(op.f('ix_fee_structures_academic_year_id'), table_name='fee_structures')
    op.drop_table('fee_structures')
    op.drop_index(op.f('ix_fee_invoices_student_id'), table_name='fee_invoices')
    op.drop_index(op.f('ix_fee_invoices_school_id'), table_name='fee_invoices')
    op.drop_index(op.f('ix_fee_invoices_academic_year_id'), table_name='fee_invoices')
    op.drop_table('fee_invoices')
    op.drop_index(op.f('ix_class_subjects_subject_id'), table_name='class_subjects')
    op.drop_index(op.f('ix_class_subjects_class_id'), table_name='class_subjects')
    op.drop_table('class_subjects')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_students_school_id'), table_name='students')
    op.drop_index(op.f('ix_students_admission_number'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_staff_payrolls_staff_id'), table_name='staff_payrolls')
    op.drop_index(op.f('ix_staff_payrolls_school_id'), table_name='staff_payrolls')
    op.drop_table('staff_payrolls')
    op.drop_index(op.f('ix_staff_leaves_staff_id'), table_name='staff_leaves')
    op.drop_index(op.f('ix_staff_leaves_school_id'), table_name='staff_leaves')
    op.drop_table('staff_leaves')
    op.drop_index(op.f('ix_staff_leave_balances_staff_id'), table_name='staff_leave_balances')
    op.drop_index(op.f('ix_staff_leave_balances_school_id'), table_name='staff_leave_balances')
    op.drop_table('staff_leave_balances')
    op.drop_index(op.f('ix_school_settings_school_id'), table_name='school_settings')
    op.drop_table('school_settings')
    op.drop_table('role_permissions')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_holidays_school_id'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_date'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_academic_year_id'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_classes_school_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_academic_year_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_admission_forms_school_id'), table_name='admission_forms')
    op.drop_index(op.f('ix_admission_forms_academic_year_id'), table_name='admission_forms')
    op.drop_table('admission_forms')
    op.drop_index(op.f('ix_admission_form_configs_school_id'), table_name='admission_form_configs')
    op.drop_index(op.f('ix_admission_form_configs_academic_year_id'), table_name='admission_form_configs')
    op.drop_table('admission_form_configs')
    op.drop_index(op.f('ix_academic_terms_school_id'), table_name='academic_terms')
    op.drop_index(op.f('ix_academic_terms_academic_year_id'), table_name='academic_terms')
    op.drop_table('academic_terms')
    op.drop_index(op.f('ix_users_school_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_school_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_staff_documents_staff_id'), table_name='staff_documents')
    op.drop_index(op.f('ix_staff_documents_school_id'), table_name='staff_documents')
    op.drop_table('staff_documents')
    op.drop_index(op.f('ix_staff_attendance_staff_id'), table_name='staff_attendance')
    op.drop_index(op.f('ix_staff_attendance_school_id'), table_name='staff_attendance')
    op.drop_index(op.f('ix_staff_attendance_date'), table_name='staff_attendance')
    op.drop_table('staff_attendance')
    op.drop_table('school_profile')
    op.drop_index(op.f('ix_roles_school_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_leave_types_school_id'), table_name='leave_types')
    op.drop_table('leave_types')
    op.drop_index(op.f('ix_fine_configurations_school_id'), table_name='fine_configurations')
    op.drop_table('fine_configurations')
    op.drop_index(op.f('ix_fee_discounts_school_id'), table_name='fee_discounts')
    op.drop_table('fee_discounts')
    op.drop_index(op.f('ix_fee_categories_school_id'), table_name='fee_categories')
    op.drop_table('fee_categories')
    op.drop_index(op.f('ix_designations_school_id'), table_name='designations')
    op.drop_table('designations')
    op.drop_index(op.f('ix_academic_years_school_id'), table_name='academic_years')
    op.drop_table('academic_years')
    op.drop_index(op.f('ix_staff_school_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_employee_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_table('schools')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_departments_school_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
