# add_all_missing_phase_tables
"""add_all_missing_phase_tables

Revision ID: 827ca77eea72
Revises: 0ea98f129719
Create Date: 2026-04-15 00:23:04.598539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.compat


# revision identifiers, used by Alembic.
revision: str = '827ca77eea72'
down_revision: Union[str, None] = '0ea98f129719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=True),
    sa.Column('max_staff', sa.Integer(), nullable=True),
    sa.Column('enabled_modules', app.models.compat.ARRAY(), nullable=False),
    sa.Column('price_monthly_paise', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admit_card_configs',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('template_name', sa.String(length=200), nullable=False),
    sa.Column('show_photo', sa.Boolean(), nullable=False),
    sa.Column('show_instructions', sa.Boolean(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('header_note', sa.Text(), nullable=True),
    sa.Column('footer_note', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admit_card_configs_school_id'), 'admit_card_configs', ['school_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('user_name', sa.String(length=200), nullable=True),
    sa.Column('role_snapshot', sa.String(length=100), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('record_type', sa.String(length=100), nullable=True),
    sa.Column('record_id', sa.Uuid(), nullable=True),
    sa.Column('record_description', sa.Text(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_module'), 'audit_logs', ['module'], unique=False)
    op.create_index(op.f('ix_audit_logs_school_id'), 'audit_logs', ['school_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('book_categories',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='book_categories_school_name_ux')
    )
    op.create_index(op.f('ix_book_categories_school_id'), 'book_categories', ['school_id'], unique=False)
    op.create_table('exam_types',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weightage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='exam_types_school_name_ux')
    )
    op.create_index(op.f('ix_exam_types_school_id'), 'exam_types', ['school_id'], unique=False)
    op.create_table('expense_categories',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget_amount', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='expense_categories_school_name_ux')
    )
    op.create_index(op.f('ix_expense_categories_school_id'), 'expense_categories', ['school_id'], unique=False)
    op.create_table('grading_scales',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ranges', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id'),
    sa.UniqueConstraint('school_id', name='grading_scales_school_ux')
    )
    op.create_table('income_categories',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='income_categories_school_name_ux')
    )
    op.create_index(op.f('ix_income_categories_school_id'), 'income_categories', ['school_id'], unique=False)
    op.create_table('inventory_categories',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='inv_categories_school_name_ux')
    )
    op.create_index(op.f('ix_inventory_categories_school_id'), 'inventory_categories', ['school_id'], unique=False)
    op.create_table('notification_templates',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('channels', sa.String(length=30), nullable=False),
    sa.Column('event_trigger', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'channels', 'event_trigger', name='notif_templates_school_ch_evt_ux')
    )
    op.create_index(op.f('ix_notification_templates_school_id'), 'notification_templates', ['school_id'], unique=False)
    op.create_table('school_feature_flags',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('feature_key', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'feature_key', name='school_feature_flags_school_key_ux')
    )
    op.create_table('school_subscriptions',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('starts_at', sa.Date(), nullable=False),
    sa.Column('ends_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('custodian_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['custodian_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_school_id'), 'stores', ['school_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_school_id'), 'suppliers', ['school_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('registration_number', sa.String(length=30), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('capacity', sa.SmallInteger(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('conductor_id', sa.Uuid(), nullable=True),
    sa.Column('insurance_expiry', sa.Date(), nullable=True),
    sa.Column('fitness_expiry', sa.Date(), nullable=True),
    sa.Column('permit_expiry', sa.Date(), nullable=True),
    sa.Column('gps_device_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['conductor_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'registration_number', name='vehicles_school_reg_ux')
    )
    op.create_index(op.f('ix_vehicles_school_id'), 'vehicles', ['school_id'], unique=False)
    op.create_table('books',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('edition', sa.String(length=50), nullable=True),
    sa.Column('publication_year', sa.SmallInteger(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('total_copies', sa.SmallInteger(), nullable=False),
    sa.Column('available_copies', sa.SmallInteger(), nullable=False),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rack_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['book_categories.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_school_id'), 'books', ['school_id'], unique=False)
    op.create_table('budget_heads',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('allocated_amount', sa.BigInteger(), nullable=False),
    sa.Column('spent_amount', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'academic_year_id', 'category_id', name='budget_heads_school_year_cat_ux')
    )
    op.create_index(op.f('ix_budget_heads_school_id'), 'budget_heads', ['school_id'], unique=False)
    op.create_table('bulk_messages',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_ids', sa.JSON(), nullable=False),
    sa.Column('target_class_id', sa.Uuid(), nullable=True),
    sa.Column('target_section_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_messages_school_id'), 'bulk_messages', ['school_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('color_tag', sa.String(length=20), nullable=True),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('audience_filter', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rule', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_school_id'), 'calendar_events', ['school_id'], unique=False)
    op.create_table('document_templates',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('template_name', sa.String(length=200), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('canvas_width_mm', sa.Float(), nullable=True),
    sa.Column('canvas_height_mm', sa.Float(), nullable=True),
    sa.Column('layout_json', sa.JSON(), nullable=True),
    sa.Column('template_html', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'template_type', 'template_name', name='doc_templates_school_type_name_ux')
    )
    op.create_index(op.f('ix_document_templates_school_id'), 'document_templates', ['school_id'], unique=False)
    op.create_table('expense_records',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('payment_mode', sa.String(length=30), nullable=True),
    sa.Column('vendor_name', sa.String(length=200), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_url', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_records_academic_year_id'), 'expense_records', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_expense_records_school_id'), 'expense_records', ['school_id'], unique=False)
    op.create_table('impersonation_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('super_admin_id', sa.Uuid(), nullable=False),
    sa.Column('impersonated_school_id', sa.Uuid(), nullable=False),
    sa.Column('impersonated_user_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['impersonated_school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['impersonated_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['super_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=True),
    sa.Column('min_stock_level', sa.Integer(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Integer(), nullable=False),
    sa.Column('is_consumable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_categories.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'item_code', name='items_school_sku_ux')
    )
    op.create_index(op.f('ix_items_school_id'), 'items', ['school_id'], unique=False)
    op.create_table('library_members',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('member_type', sa.String(length=10), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('max_books_allowed', sa.SmallInteger(), nullable=False),
    sa.Column('membership_valid_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'member_id', name='library_members_school_mid_ux')
    )
    op.create_index(op.f('ix_library_members_school_id'), 'library_members', ['school_id'], unique=False)
    op.create_table('notifications',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_school_id'), 'notifications', ['school_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('ptm_events',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ptm_date', sa.Date(), nullable=False),
    sa.Column('slot_duration_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ptm_events_school_id'), 'ptm_events', ['school_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('expected_delivery', sa.Date(), nullable=True),
    sa.Column('actual_delivery', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'po_number', name='po_school_number_ux')
    )
    op.create_index(op.f('ix_purchase_orders_school_id'), 'purchase_orders', ['school_id'], unique=False)
    op.create_table('report_card_templates',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('template_name', sa.String(length=200), nullable=False),
    sa.Column('exam_type_id', sa.Uuid(), nullable=True),
    sa.Column('layout_config', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['exam_type_id'], ['exam_types.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_card_templates_school_id'), 'report_card_templates', ['school_id'], unique=False)
    op.create_table('routes',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='routes_school_name_ux')
    )
    op.create_index(op.f('ix_routes_school_id'), 'routes', ['school_id'], unique=False)
    op.create_table('vehicle_fuel_log',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('fuel_date', sa.Date(), nullable=False),
    sa.Column('fuel_quantity', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fuel_cost', sa.Integer(), nullable=False),
    sa.Column('odometer_reading', sa.Integer(), nullable=True),
    sa.Column('pump_name', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_fuel_log_school_id'), 'vehicle_fuel_log', ['school_id'], unique=False)
    op.create_index(op.f('ix_vehicle_fuel_log_vehicle_id'), 'vehicle_fuel_log', ['vehicle_id'], unique=False)
    op.create_table('vehicle_maintenance',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('maintenance_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('maintenance_date', sa.Date(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=True),
    sa.Column('odometer_reading', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_maintenance_school_id'), 'vehicle_maintenance', ['school_id'], unique=False)
    op.create_index(op.f('ix_vehicle_maintenance_vehicle_id'), 'vehicle_maintenance', ['vehicle_id'], unique=False)
    op.create_table('book_issues',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('issued_by', sa.Uuid(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('fine_per_day', sa.BigInteger(), nullable=True),
    sa.Column('fine_amount', sa.BigInteger(), nullable=False),
    sa.Column('fine_paid', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['library_members.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_issues_book_id'), 'book_issues', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_issues_member_id'), 'book_issues', ['member_id'], unique=False)
    op.create_index(op.f('ix_book_issues_school_id'), 'book_issues', ['school_id'], unique=False)
    op.create_table('message_logs',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('bulk_message_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_user_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_phone', sa.String(length=20), nullable=True),
    sa.Column('recipient_email', sa.String(length=200), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('event_trigger', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gateway_response', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bulk_message_id'], ['bulk_messages.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_logs_school_id'), 'message_logs', ['school_id'], unique=False)
    op.create_table('ptm_slots',
    sa.Column('ptm_event_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('slot_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slot_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ptm_event_id'], ['ptm_events.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ptm_slots_ptm_event_id'), 'ptm_slots', ['ptm_event_id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('po_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_entries',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_entries_item_id'), 'stock_entries', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_entries_school_id'), 'stock_entries', ['school_id'], unique=False)
    op.create_table('stock_issues',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('issued_to', sa.Uuid(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('issued_by', sa.Uuid(), nullable=True),
    sa.Column('returned_quantity', sa.Integer(), nullable=False),
    sa.Column('return_deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issued_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_issues_item_id'), 'stock_issues', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_issues_school_id'), 'stock_issues', ['school_id'], unique=False)
    op.create_table('stops',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('stop_order', sa.SmallInteger(), nullable=False),
    sa.Column('pickup_time', sa.Time(), nullable=True),
    sa.Column('drop_time', sa.Time(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('fare', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'stop_order', name='stops_route_order_ux')
    )
    op.create_index(op.f('ix_stops_route_id'), 'stops', ['route_id'], unique=False)
    op.create_index(op.f('ix_stops_school_id'), 'stops', ['school_id'], unique=False)
    op.create_table('announcements',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.Text(), nullable=True),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('target_class_id', sa.Uuid(), nullable=True),
    sa.Column('target_section_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['target_class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['target_section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_school_id'), 'announcements', ['school_id'], unique=False)
    op.create_table('exams',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=True),
    sa.Column('exam_type_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('room_number', sa.String(length=20), nullable=True),
    sa.Column('invigilator_id', sa.Uuid(), nullable=True),
    sa.Column('full_marks', sa.SmallInteger(), nullable=False),
    sa.Column('pass_marks', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['exam_type_id'], ['exam_types.id'], ),
    sa.ForeignKeyConstraint(['invigilator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'academic_year_id', 'exam_type_id', 'class_id', 'subject_id', name='exams_school_year_type_class_subject_ux')
    )
    op.create_index(op.f('ix_exams_academic_year_id'), 'exams', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_exams_class_id'), 'exams', ['class_id'], unique=False)
    op.create_index(op.f('ix_exams_exam_type_id'), 'exams', ['exam_type_id'], unique=False)
    op.create_index(op.f('ix_exams_school_id'), 'exams', ['school_id'], unique=False)
    op.create_table('homework',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homework_class_id'), 'homework', ['class_id'], unique=False)
    op.create_index(op.f('ix_homework_school_id'), 'homework', ['school_id'], unique=False)
    op.create_table('lesson_plans',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('period_number', sa.SmallInteger(), nullable=False),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('resources', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'subject_id', 'plan_date', 'period_number', name='lesson_plans_cls_subj_date_period_ux')
    )
    op.create_index(op.f('ix_lesson_plans_school_id'), 'lesson_plans', ['school_id'], unique=False)
    op.create_table('ptm_bookings',
    sa.Column('slot_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['ptm_slots.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id')
    )
    op.create_table('student_transport',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('stop_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'academic_year_id', name='student_transport_student_year_ux')
    )
    op.create_index(op.f('ix_student_transport_school_id'), 'student_transport', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_transport_student_id'), 'student_transport', ['student_id'], unique=False)
    op.create_table('homework_submissions',
    sa.Column('homework_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('marks_given', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('homework_id', 'student_id', name='hw_submissions_hw_student_ux')
    )
    op.create_index(op.f('ix_homework_submissions_homework_id'), 'homework_submissions', ['homework_id'], unique=False)
    op.create_index(op.f('ix_homework_submissions_student_id'), 'homework_submissions', ['student_id'], unique=False)
    op.create_table('income_records',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('income_date', sa.Date(), nullable=False),
    sa.Column('payment_mode', sa.String(length=30), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('received_by', sa.Uuid(), nullable=True),
    sa.Column('is_fee_income', sa.Boolean(), nullable=False),
    sa.Column('fee_payment_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['income_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fee_payment_id'], ['fee_payments.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_records_academic_year_id'), 'income_records', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_income_records_school_id'), 'income_records', ['school_id'], unique=False)
    op.create_table('student_marks',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('marks_obtained', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_absent', sa.Boolean(), nullable=False),
    sa.Column('is_exempted', sa.Boolean(), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('entered_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'student_id', name='student_marks_exam_student_ux')
    )
    op.create_index(op.f('ix_student_marks_exam_id'), 'student_marks', ['exam_id'], unique=False)
    op.create_index(op.f('ix_student_marks_school_id'), 'student_marks', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_marks_student_id'), 'student_marks', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_marks_student_id'), table_name='student_marks')
    op.drop_index(op.f('ix_student_marks_school_id'), table_name='student_marks')
    op.drop_index(op.f('ix_student_marks_exam_id'), table_name='student_marks')
    op.drop_table('student_marks')
    op.drop_index(op.f('ix_income_records_school_id'), table_name='income_records')
    op.drop_index(op.f('ix_income_records_academic_year_id'), table_name='income_records')
    op.drop_table('income_records')
    op.drop_index(op.f('ix_homework_submissions_student_id'), table_name='homework_submissions')
    op.drop_index(op.f('ix_homework_submissions_homework_id'), table_name='homework_submissions')
    op.drop_table('homework_submissions')
    op.drop_index(op.f('ix_student_transport_student_id'), table_name='student_transport')
    op.drop_index(op.f('ix_student_transport_school_id'), table_name='student_transport')
    op.drop_table('student_transport')
    op.drop_table('ptm_bookings')
    op.drop_index(op.f('ix_lesson_plans_school_id'), table_name='lesson_plans')
    op.drop_table('lesson_plans')
    op.drop_index(op.f('ix_homework_school_id'), table_name='homework')
    op.drop_index(op.f('ix_homework_class_id'), table_name='homework')
    op.drop_table('homework')
    op.drop_index(op.f('ix_exams_school_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_exam_type_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_class_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_academic_year_id'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_announcements_school_id'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_stops_school_id'), table_name='stops')
    op.drop_index(op.f('ix_stops_route_id'), table_name='stops')
    op.drop_table('stops')
    op.drop_index(op.f('ix_stock_issues_school_id'), table_name='stock_issues')
    op.drop_index(op.f('ix_stock_issues_item_id'), table_name='stock_issues')
    op.drop_table('stock_issues')
    op.drop_index(op.f('ix_stock_entries_school_id'), table_name='stock_entries')
    op.drop_index(op.f('ix_stock_entries_item_id'), table_name='stock_entries')
    op.drop_table('stock_entries')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_ptm_slots_ptm_event_id'), table_name='ptm_slots')
    op.drop_table('ptm_slots')
    op.drop_index(op.f('ix_message_logs_school_id'), table_name='message_logs')
    op.drop_table('message_logs')
    op.drop_index(op.f('ix_book_issues_school_id'), table_name='book_issues')
    op.drop_index(op.f('ix_book_issues_member_id'), table_name='book_issues')
    op.drop_index(op.f('ix_book_issues_book_id'), table_name='book_issues')
    op.drop_table('book_issues')
    op.drop_index(op.f('ix_vehicle_maintenance_vehicle_id'), table_name='vehicle_maintenance')
    op.drop_index(op.f('ix_vehicle_maintenance_school_id'), table_name='vehicle_maintenance')
    op.drop_table('vehicle_maintenance')
    op.drop_index(op.f('ix_vehicle_fuel_log_vehicle_id'), table_name='vehicle_fuel_log')
    op.drop_index(op.f('ix_vehicle_fuel_log_school_id'), table_name='vehicle_fuel_log')
    op.drop_table('vehicle_fuel_log')
    op.drop_index(op.f('ix_routes_school_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_report_card_templates_school_id'), table_name='report_card_templates')
    op.drop_table('report_card_templates')
    op.drop_index(op.f('ix_purchase_orders_school_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_ptm_events_school_id'), table_name='ptm_events')
    op.drop_table('ptm_events')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_school_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_library_members_school_id'), table_name='library_members')
    op.drop_table('library_members')
    op.drop_index(op.f('ix_items_school_id'), table_name='items')
    op.drop_table('items')
    op.drop_table('impersonation_logs')
    op.drop_index(op.f('ix_expense_records_school_id'), table_name='expense_records')
    op.drop_index(op.f('ix_expense_records_academic_year_id'), table_name='expense_records')
    op.drop_table('expense_records')
    op.drop_index(op.f('ix_document_templates_school_id'), table_name='document_templates')
    op.drop_table('document_templates')
    op.drop_index(op.f('ix_calendar_events_school_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_bulk_messages_school_id'), table_name='bulk_messages')
    op.drop_table('bulk_messages')
    op.drop_index(op.f('ix_budget_heads_school_id'), table_name='budget_heads')
    op.drop_table('budget_heads')
    op.drop_index(op.f('ix_books_school_id'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_vehicles_school_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_suppliers_school_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_stores_school_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_table('school_subscriptions')
    op.drop_table('school_feature_flags')
    op.drop_index(op.f('ix_notification_templates_school_id'), table_name='notification_templates')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_inventory_categories_school_id'), table_name='inventory_categories')
    op.drop_table('inventory_categories')
    op.drop_index(op.f('ix_income_categories_school_id'), table_name='income_categories')
    op.drop_table('income_categories')
    op.drop_table('grading_scales')
    op.drop_index(op.f('ix_expense_categories_school_id'), table_name='expense_categories')
    op.drop_table('expense_categories')
    op.drop_index(op.f('ix_exam_types_school_id'), table_name='exam_types')
    op.drop_table('exam_types')
    op.drop_index(op.f('ix_book_categories_school_id'), table_name='book_categories')
    op.drop_table('book_categories')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_school_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_module'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admit_card_configs_school_id'), table_name='admit_card_configs')
    op.drop_table('admit_card_configs')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
