# add_missing_round3_tables
"""add_missing_round3_tables

Revision ID: 0ea98f129719
Revises: 70df5e4506d5
Create Date: 2026-04-15 00:18:10.430101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ea98f129719'
down_revision: Union[str, None] = '70df5e4506d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
