"""SQLAlchemy model for multi-turn conversation sessions (chat flow engine)."""
from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, Optional

from sqlalchemy import String, Text, DateTime, Boolean, Index
from sqlalchemy.orm import Mapped, mapped_column

from app.db.session import Base


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _expires_default() -> datetime:
    return datetime.now(timezone.utc) + timedelta(hours=24)


class ConversationSession(Base):
    """Stores the state of a multi-turn chatbot conversation.

    session_id  — UUID generated by client (web) or phone number (WhatsApp).
    channel     — 'web' | 'whatsapp'
    current_flow — Active flow key e.g. 'greeting', 'student_attendance', …
    current_step — Step within the flow e.g. 'select_class', 'mark_students', …
    context      — JSON blob holding flow-specific scratch data (selected class, etc.)
    expires_at   — Sessions auto-expire after 24 h of inactivity.
    """

    __tablename__ = "conversation_sessions"

    # Use String(36) for the PK since it's a client-provided UUID-string or phone number
    id: Mapped[str] = mapped_column(String(100), primary_key=True)
    user_id: Mapped[Optional[str]] = mapped_column(String(36), nullable=True, index=True)
    school_id: Mapped[Optional[str]] = mapped_column(String(36), nullable=True, index=True)
    channel: Mapped[str] = mapped_column(String(20), nullable=False, default="web")

    current_flow: Mapped[Optional[str]] = mapped_column(String(60), nullable=True)
    current_step: Mapped[Optional[str]] = mapped_column(String(60), nullable=True)
    context_json: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow, nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow, onupdate=_utcnow, nullable=False
    )
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_expires_default, nullable=False
    )

    __table_args__ = (
        Index("ix_conv_session_user_channel", "user_id", "channel"),
    )

    # ── Helpers ────────────────────────────────────────────────────────────

    @property
    def context(self) -> Dict[str, Any]:
        if not self.context_json:
            return {}
        try:
            return json.loads(self.context_json)
        except Exception:
            return {}

    def set_context(self, data: Dict[str, Any]) -> None:
        self.context_json = json.dumps(data)

    def patch_context(self, patch: Dict[str, Any]) -> None:
        ctx = self.context
        ctx.update(patch)
        self.context_json = json.dumps(ctx)

    def touch(self) -> None:
        """Extend session expiry by another 24 h."""
        self.updated_at = _utcnow()
        self.expires_at = _expires_default()

    @property
    def is_expired(self) -> bool:
        return datetime.now(timezone.utc) > self.expires_at.replace(tzinfo=timezone.utc)
